web:
  build: .
  ports:
  - 10002:80
  links:
  - mysql
  - redis
  volumes:
  - .:/site

mysql:
    image: mysql:5.6
    command: mysqld --user=root --verbose --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
    ports:
    - 20042:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

redis:
  image: redis